
[ClassVersion("1.0.0.0"), FriendlyName("ChocolateySoftware")]
class ChocolateySoftware : OMI_BaseResource
{
    [Key, Description("Specifies whether the Chocolatey Software should be installed on the machine or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Optional package URL to download a specific Chocolatey Software package.")] String ChocolateyPackageUrl;
    [Write, Description("Url of a Nuget feed where the Chocolatey software package is available. i.e. https://chocolatey.org/api/v2")] String PackageFeedUrl;
    [Write, Description("Specific version of package available on the nuget Package Feed Url provided.")] String Version;
    [Write, Description("Chocolatey Temp directory to unzip downloaded package during bootstrap.")] String ChocoTempDir;
    [Write, Description("Url of the proxy to use to download the Chocolatey binaries.")] String ProxyLocation;
    [Write, EmbeddedInstance("MSFT_Credential"), Description("Credential to be used to authenticate to the Proxy for downloading the Chocolatey Package.")] String ProxyCredential;
    [Write, Description("Ignore proxy during download.")] Boolean IgnoreProxy;
    [Write, Description("Path where Chocolatey should be installed, default to `$Env:ChocolateyInstall or C:\\ProgramData\\Chocolatey")] String InstallationDirectory;
};

