
[ClassVersion("1.0.0.0"), FriendlyName("ChocolateyFeature")]
class ChocolateyFeature : OMI_BaseResource
{
    [Required, Description("Specifies whether the Chocolatey Feature should be enabled or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Key] String Name;
    [Read] boolean enabled;
    [Read] String SetExplicitly;
    [Read] String Description;
};

