
[ClassVersion("1.0.0.0"), FriendlyName("ChocolateyPackage")]
class ChocolateyPackage : OMI_BaseResource
{
    [Required, Description("Specifies whether the Chocolatey Package should be installed on the machine or not."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Key, Description("Chocolatey Package Id")] String Name;
    [Write, Description("Chocolatey Package Version")] String Version;
    [Write, EmbeddedInstance("MSFT_KeyValuePair"), Description("Chocolatey Options")] String ChocolateyOptions[];
    [Write, Description("Only updates installed package and ignores packages not Installed.")] boolean UpdateOnly;
};

